"""Hardcoded weekly focus and per-lesson goal/task text.

This content must be returned to the user verbatim, never paraphrased or
regenerated by the LLM, so it lives here as plain data and is served through
a code-level override in coach/agent.py (see detect_lesson_goal_request,
detect_week_focus_request, detect_generic_weekly_query).
"""

from typing import Dict

LESSON_GOALS: Dict[int, str] = {
    1: (
        "Go to the \"Goals\" page and choose a \"Suggested Goal\" or create your own physical "
        "activity goal for the week, an aerobic, strength, or balance activity that feels "
        "realistic and enjoyable for you."
    ),
    2: (
        "Check in on your goal from this week. Go to the \"Goals\" page to mark it complete or "
        "set a new goal before your next lesson."
    ),
    3: (
        "Go to the \"Goals\" page and lock in a \"Suggested Goal\" or set a custom goal, keeping "
        "the recommendation of moderate-to-vigorous physical activity per week in mind."
    ),
    4: (
        "Check in on your goal. Go to the \"Goals\" page to mark it complete or set your next "
        "goal, and think about what else you can do this week to reach your "
        "moderate-to-vigorous physical activity goal."
    ),
    5: (
        "Set your next goal. Go to the \"Goals\" page and select a \"Suggested Goal\" or create "
        "one that fits your schedule, ideally working toward the moderate-to-vigorous physical "
        "activity recommendation each week."
    ),
    6: (
        "Go to the \"Goals\" page to mark your goal complete or set your next goal. Reflect on "
        "what else you could do this week to move closer to your moderate-to-vigorous physical "
        "activity goal."
    ),
}

WEEK_FOCUS: Dict[int, str] = {
    1: "This week's focus: Choose your starting goal. Lessons to complete: 1 and 2.",
    2: "This week's focus: Shape a goal that fits your life. Lessons to complete: 3 and 4.",
    3: "This week's focus: Keep going and notice your progress. Lessons to complete: 5 and 6.",
}

LESSON_TO_WEEK: Dict[int, int] = {1: 1, 2: 1, 3: 2, 4: 2, 5: 3, 6: 3}

OUT_OF_RANGE_MESSAGE = (
    "Sorry, I can't answer that. I can talk about lessons 1-6 and the science behind them, including the reflective and regulatory sides of the M-PAC framework (why to be active, how it feels, and how to turn intentions into action)."
)

CLARIFYING_QUESTION = "Which lesson (or week) number are you currently on?"


def ambiguous_number_question(num: int) -> str:
    """Ask whether a bare number refers to a lesson or a week."""
    return f"Did you mean lesson {num} or week {num}?"
